export let data = [
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120002",
        "categories": ["hands", "hygiene"],
        "img": "img/aos.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097548",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120003",
        "categories": ["hygiene"],
        "img": "img/ariel.png",
        "icon": "img/productCard_box.svg",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "г",
        "weight": 28.8,
        "barcode": "4604049097549",
        "manufacturer": "Grifon",
        "brand": "GRIFON",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 45.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120004",
        "categories": ["hygiene", "gifts"],
        "img": "img/biMax.png",
        "icon": "img/productCard_box.svg",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097550",
        "manufacturer": "Paclan",
        "brand": "Nivea",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 67.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120005",
        "categories": ["hands", "hygiene", "body"],
        "img": "img/bioMio.png",
        "icon": "img/productCard_box.svg",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097551",
        "manufacturer": "Булгари Грин",
        "brand": "Домашний сундук",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 30.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120006",
        "categories": ["hands"],
        "img": "img/sorti.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097552",
        "manufacturer": "Boyscout",
        "brand": "HELP",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 50.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120007",
        "categories": ["hands"],
        "img": "img/aos.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097553",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120008",
        "categories": [],
        "img": "img/ariel.png",
        "icon": "img/productCard_box.svg",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "г",
        "weight": 28.8,
        "barcode": "4604049097554",
        "manufacturer": "Grifon",
        "brand": "GRIFON",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 45.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120009",
        "categories": [],
        "img": "img/biMax.png",
        "icon": "img/productCard_box.svg",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097555",
        "manufacturer": "Paclan",
        "brand": "Nivea",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 67.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120010",
        "categories": ["hands", "hygiene", "body"],
        "img": "img/bioMio.png",
        "icon": "img/productCard_box.svg",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097556",
        "manufacturer": "Булгари Грин",
        "brand": "Домашний сундук",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 30.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120011",
        "categories": ["hands", "hygiene"],
        "img": "img/sorti.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097557",
        "manufacturer": "Boyscout",
        "brand": "HELP",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 50.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120012",
        "categories": ["hands"],
        "img": "img/aos.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097558",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120013",
        "categories": [],
        "img": "img/ariel.png",
        "icon": "img/productCard_box.svg",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "г",
        "weight": 28.8,
        "barcode": "4604049097559",
        "manufacturer": "Grifon",
        "brand": "GRIFON",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 45.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120014",
        "categories": [],
        "img": "img/biMax.png",
        "icon": "img/productCard_box.svg",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097560",
        "manufacturer": "Paclan",
        "brand": "Nivea",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 67.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120015",
        "categories": ["hands", "hygiene", "body"],
        "img": "img/bioMio.png",
        "icon": "img/productCard_box.svg",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097561",
        "manufacturer": "Булгари Грин",
        "brand": "Домашний сундук",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 30.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120016",
        "categories": ["hands", "hygiene"],
        "img": "img/sorti.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097562",
        "manufacturer": "Boyscout",
        "brand": "HELP",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 50.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120017",
        "categories": ["hands"],
        "img": "img/aos.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097563",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120018",
        "categories": [],
        "img": "img/ariel.png",
        "icon": "img/productCard_box.svg",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "г",
        "weight": 28.8,
        "barcode": "4604049097564",
        "manufacturer": "Grifon",
        "brand": "GRIFON",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 45.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120019",
        "categories": ["hygiene"],
        "img": "img/biMax.png",
        "icon": "img/productCard_box.svg",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097565",
        "manufacturer": "Paclan",
        "brand": "Nivea",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 67.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120020",
        "categories": ["hands", "hygiene", "body"],
        "img": "img/bioMio.png",
        "icon": "img/productCard_box.svg",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "г",
        "weight": 1500,
        "barcode": "4604049097566",
        "manufacturer": "Булгари Грин",
        "brand": "Домашний сундук",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 30.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120021",
        "categories": ["hands", "hygiene"],
        "img": "img/sorti.png",
        "icon": "img/productCard_bottle.svg",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097567",
        "manufacturer": "Boyscout",
        "brand": "HELP",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 50.76,
    },
];
