export let data = [
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120002",
        "categories": ["hands"],
        "img": "img/aos.png",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097548",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120003",
        "categories": [],
        "img": "img/ariel.png",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "гр",
        "weight": 28.8,
        "barcode": "4604049097549",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120004",
        "categories": [],
        "img": "img/biMax.png",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097550",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120005",
        "categories": ["hands"],
        "img": "img/bioMio.png",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097551",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120006",
        "categories": ["hands"],
        "img": "img/sorti.png",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097552",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120007",
        "categories": ["hands"],
        "img": "img/aos.png",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097553",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120008",
        "categories": [],
        "img": "img/ariel.png",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "гр",
        "weight": 28.8,
        "barcode": "4604049097554",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120009",
        "categories": [],
        "img": "img/biMax.png",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097555",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120010",
        "categories": ["hands"],
        "img": "img/bioMio.png",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097556",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120011",
        "categories": ["hands"],
        "img": "img/sorti.png",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097557",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120012",
        "categories": ["hands"],
        "img": "img/aos.png",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097558",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120013",
        "categories": [],
        "img": "img/ariel.png",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "гр",
        "weight": 28.8,
        "barcode": "4604049097559",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120014",
        "categories": [],
        "img": "img/biMax.png",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097560",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120015",
        "categories": ["hands"],
        "img": "img/bioMio.png",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097561",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120016",
        "categories": ["hands"],
        "img": "img/sorti.png",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097562",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120017",
        "categories": ["hands"],
        "img": "img/aos.png",
        "title": "AOS средство для мытья посуды Crystal",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097563",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120018",
        "categories": [],
        "img": "img/ariel.png",
        "title": "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
        "unit": "гр",
        "weight": 28.8,
        "barcode": "4604049097564",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120019",
        "categories": [],
        "img": "img/biMax.png",
        "title": "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097565",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120020",
        "categories": ["hands"],
        "img": "img/bioMio.png",
        "title": "BioMio BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
        "unit": "гр",
        "weight": 1500,
        "barcode": "4604049097566",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
    {
        "id": "730718ae-6c31-11ed-a1eb-0242ac120021",
        "categories": ["hands"],
        "img": "img/sorti.png",
        "title": "AOS Ср-во для мытья посуды Апельсин+мята",
        "unit": "мл",
        "weight": 450,
        "barcode": "4604049097567",
        "manufacturer": "Нэфис",
        "brand": "AOS",
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
        "price": 48.76,
    },
];
